# OpenSRF / Evergreen Ansible Installer Playbook
# Author: Bill Erickson <berickxx@gmail.com>

- hosts: '{{hosts}}'
  remote_user: '{{deploy_user}}'
  become_method: sudo
  vars_files:
    - settings.yml
    - local_settings.yml
  tasks:
  - name: Restart memcached
    become: true
    service: name=memcached state=restarted
  - name: Start OpenSRF
    become: true
    service: name=opensrf state=restarted
  - name: Running Autogen
    become: true
    become_user: opensrf
    environment:
      PATH: "{{ansible_env.PATH}}:{{eg_install_path}}/bin"
    shell: autogen.sh
  - name: Start Apache
    become: true
    service: name=apache2 state=restarted
  - name: Start websockets
    become: true
    service: name=websocketd-osrf state=restarted
