# OpenSRF / Evergreen Ansible Installer Playbook
# Author: Bill Erickson <berickxx@gmail.com>

- hosts: '{{hosts}}'
  remote_user: '{{deploy_user}}'
  become_method: sudo
  vars_files:
    - settings.yml
    - local_settings.yml
  tasks:
  - name: Stop Apache
    become: true
    service: name=apache2 state=stopped
  - name: Stop OpenSRF
    become: true
    service: name=opensrf state=stopped
  - name: Stop Websocketd
    become: true
    service: name=websocketd-osrf state=stopped
  - name: Process OpenSRF Tasks
    include: opensrf/main.yml
  - name: Process Evergreen Tasks
    include: evergreen-upgrade/main.yml
  - name: Process Optional Items
    include: extras/main.yml
