- name: Install OpenSRF Service File
  become: true
  template: 
    src: extras/service-files/opensrf.service.j2
    dest: /lib/systemd/system/opensrf.service 
    owner: root
    group: root
    mode: 0644
- name: Install OpenSRF Websocketd Service File
  become: true
  template: 
    src: extras/service-files/websocketd-osrf.service.j2
    dest: /lib/systemd/system/websocketd-osrf.service
    owner: root
    group: root
    mode: 0644
- name: Install Evergreen Reporter Service File
  become: true
  template: 
    src: extras/service-files/evergreen-reporter.service.j2
    dest: /lib/systemd/system/evergreen-reporter.service 
    owner: root
    group: root
    mode: 0644
- name: Reload Systemd Configs
  become: true
  shell: systemctl daemon-reload
- name: Enable OpenSRF Service
  become: true
  shell: systemctl enable opensrf
- name: Enable OpenSRF Websocketd Service
  become: true
  shell: systemctl enable websocketd-osrf
- name: Enable Evergreen Reporter Service
  become: true
  shell: systemctl enable evergreen-reporter

